### PR TITLE
fix: add npm registry fallback to the lookupRange 

### LINKED ISSUE #189: Version lookups not working for packages not yet built
We have build queue requests to the build queue JSPM API built into the generator, but these only apply for packages that are known versions.

The version resolver itself in the generator will throw a version not found lookup error for versions not yet built.

The best way to resolve this is likely to update the version resolver itself to not depend on the build status of a package, but instead to use the npm registry resolver source of truth directly.

Then if a package build is missing we can properly throw an error about this, instead of a version resolution error.

### PR DESCRIPTION
**Pull request by Aslemammad**
Resolves #189

### CODE REVIEW

File: src/providers/jspm.ts [hunk 1]
```diff
@@ -174,15 +176,23 @@ export async function resolveLatestTarget (this: Resolver, target: LatestPackage
 function pkgToLookupUrl (pkg: ExactPackage, edge = false) {
   return `${cdnUrl}${pkg.registry}:${pkg.name}${pkg.version ? '@' + pkg.version : edge ? '@' : ''}`;
 }
-async function lookupRange (this: Resolver, registry: string, name: string, range: string, unstable: boolean, parentUrl?: string): Promise<ExactPackage | null> {
+async function lookupRange (this: Resolver, registry: string, name: string, range: string, semverRange: SemverRange, unstable: boolean, parentUrl?: string): Promise<ExactPackage | null> {
```
Comment (guybedford) [inline src/providers/jspm.ts:179]: Let's not add this argument.

Instead, do `const semverRange = new SemverRange(range || '*')` then ensure to use the `unstable` boolean to determine if you want to do unstable or stable inclusion for the range (this is the second argument to the `.has` function - https://www.npmjs.com/package/sver - `range.has(version: Semver|string, unstable = false): bool: Whether the range includes the given version.`)

File: src/providers/jspm.ts [hunk 2]
```diff
@@ -174,15 +176,23 @@ export async function resolveLatestTarget (this: Resolver, target: LatestPackage
...
   const res = await fetch(pkgToLookupUrl({ registry, name, version: range }, unstable), this.fetchOpts);
   switch (res.status) {
     case 304:
     case 200:
       return { registry, name, version: (await res.text()).trim() };
     case 404:
+      const registryLookup = await (await fetch(`https://registry.npmjs.org/${name}`, {})).json()
```
Comment (guybedford) [inline src/providers/jspm.ts:186]: This needs to be memoized.

File: src/providers/jspm.ts [hunk 3]
```diff
@@ -181,8 +183,28 @@ async function lookupRange (this: Resolver, registry: string, name: string, rang
...
   }
 }
+
+const versionsCacheMap = new Map<string, string[]>()
+
+async function fetchVersions(name: string): Promise<string[]> {
+  if (versionsCacheMap.has(name)) {
+    return versionsCacheMap.get(name);
+  }
+  const registryLookup = await (await fetch(`https://registry.npmjs.org/${name}`, {})).json();
```
Comment (guybedford) [inline src/providers/jspm.ts:205]: I believe this should fix the failing test?

```suggestion
  const registryLookup = await (await fetch(`https://npmlookup.jspm.io/${encodeURI(name)}`)).json();
```

File: src/providers/jspm.ts [hunk 4]
```diff
@@ -181,8 +183,28 @@ async function lookupRange (this: Resolver, registry: string, name: string, rang
     case 200:
       return { registry, name, version: (await res.text()).trim() };
     case 404:
+      const versions = await fetchVersions(name)
+      const semverRange = new SemverRange(range || '*', unstable)
+      const version = versions.find(v => semverRange.has(v))
+
+      if (version) {
+        return { registry, name, version };
```
Comment (guybedford) [inline src/providers/jspm.ts:191]: What error message does this lead to? It would be good to verify an example and check if it improves error usability (which is the point of this work).

File: src/providers/jspm.ts [hunk 5]
```diff
@@ -181,8 +183,28 @@ async function lookupRange (this: Resolver, registry: string, name: string, rang
     case 200:
       return { registry, name, version: (await res.text()).trim() };
     case 404:
+      const versions = await fetchVersions(name)
+      const semverRange = new SemverRange(range || '*', unstable)
+      const version = versions.find(v => semverRange.has(v))
```
Comment (guybedford) [inline src/providers/jspm.ts:188]: We mustn't "find" the first match, we must match the best version to the semver. This is done via:

```suggestion
      const version = semverRange.bestMatch(versions, unstable);
```

We also need to handle the version not found case properly - the not found error is as important as the not built error.

**Review by guybedford — COMMENTED** [review]
Apologies for the delayed review here, see the comments.

File: src/providers/jspm.ts [hunk 6]
```diff
@@ -181,8 +183,25 @@ async function lookupRange (this: Resolver, registry: string, name: string, rang
     case 200:
       return { registry, name, version: (await res.text()).trim() };
     case 404:
-      return null;
+      const versions = await fetchVersions(name)
+      const semverRange = new SemverRange(range || '*', unstable)
+      const version = semverRange.bestMatch(versions, unstable);
+
+      return { registry, name, version };
```
Comment (guybedford) [inline src/providers/jspm.ts:190]: I believe the condition check is still needed even with `bestMatch` since there might be no match.

Comment (Aslemammad) [reply src/providers/jspm.ts]: Yep, I resolved it and added a test case.

File: src/providers/jspm.ts (hunk 4 above)
Comment (guybedford) [reply src/providers/jspm.ts:191]: Nice, thanks for adding the error.

**Review by guybedford — APPROVED** [review]
Great! Let's land.
