### PR TITLE
fix: hook into deno.json for deno dependencies

### LINKED ISSUE #289: Hook into `deno.json` when resolving dependencies for denoland packages.
```
$ jspm i denoland:fresh/runtime.ts

Error: Deno provider does not support the npm registry for package "preact" - perhaps you mean to install "denoland:preact"?
```

`fresh` uses an import map for bare specifiers like `preact`, but the generator currently ignores the `deno.json`, so when it tries to resolve `preact` we hit the global fallback, which is to use `npm:preact`, and the deno provider throws as it doesn't support the npm registry.

### PR DESCRIPTION
**Pull request by Bubblyworld**
Fixes #289, or at least a first pass of a fix. This does the simplest thing for
now, which is to use the top-level imports for resolving a deno package's
secondary dependencies. This gets the `denoland:fresh/runtime.ts` example
working, for instance.

### CODE REVIEW

File: src/providers/deno.ts [hunk 1]
```diff
@@ -148,6 +149,41 @@ export async function getPackageConfig(
...
+  const pkgJsonUrl = new URL("package.json", pkgUrl);
+  const pkgRes = await fetch(pkgJsonUrl.href, this.fetchOpts);
+  switch (pkgRes.status) {
+    case 200:
+    case 304:
+      return (await pkgRes.json()) as PackageConfig;
+  }
+
+  // If there's a deno.json, read off the top-level imports as deps:
+  const denoJsonUrl = new URL("deno.json", pkgUrl);
```
Comment (guybedford) [inline src/providers/deno.ts:163]: Unfortunately this is absolute not how to use import maps for package management. That would be like using lock files to resolve dependencies instead of the package.json file.

The problem instead is resolving unknown dependencies against the default provider and default registry. In this case it's already defaulting to the `npm` registry, so the only problem we have to fix here is why it's trying to use the deno provider to resolve the npm registry, when it should never be possible to do that.

File: src/providers/deno.ts [hunk 2]
```diff
@@ -148,6 +149,41 @@ export async function getPackageConfig(
       },
     };
   }
+
+  // If there's a package.json, return that:
+  const pkgJsonUrl = new URL("package.json", pkgUrl);
```
Comment (guybedford) [inline src/providers/deno.ts:154]: This is a great catch, thanks.

File: src/install/installer.ts [hunk 3]
```diff
@@ -112,6 +112,14 @@ export class Installer {
     if (opts.defaultProvider)
       this.defaultProvider = parseProviderStr(opts.defaultProvider);
     this.providers = Object.assign({}, registryProviders);
+
+    // TODO: this is a hack, as we currently don't have proper support for
+    // providers owning particular registries. The proper way to do this would
+    // be to have each provider declare what registries it supports, and
+    // construct a providers mapping at init when we detect default provider:
+    if (opts.defaultProvider.includes("deno"))
+      this.providers["npm:"] = "jspm.io";
```
Comment (guybedford) [inline src/install/installer.ts:121]: Perhaps only override `this.providers['npm:']` if it doesn't already exist? But yes, this seems fine for now.

**Review by guybedford — APPROVED** [review]
LGTM
