### PR TITLE
Fix bug when tracing/uninstalling the base package.

### LINKED ISSUE #204: Linking and uninstalling self fails to remove top-level import.
Suppose you have the following `package.json`:

```json
{
  "name": "localpkg",
  "exports": "./index.js"
}
```

Calling `traceInstall(...)` followed by `uninstall(...)` should result in an empty import map, but in the case you install the self-reference `"localpkg"` and then uninstall it with a separate generator instance, it fails:

```js
let generator = new Generator({
  defaultProvider: 'jspm',
  env: ['production', 'browser']
});

await generator.traceInstall('localpkg');
let map = generator.getMap();


generator = new Generator({
  defaultProvider: 'jspm',
  env: ['production', 'browser'],
  inputMap: map,
});

await generator.uninstall('localpkg');
map = generator.getMap(); // this is not empty!
```

### PR DESCRIPTION
**Pull request by Bubblyworld**
Fixes #204. The bug is basically that when linking the base package itself,
the only thing the tracemap does is record the base package as a pin. When
you then try and load the resulting input map, the base package specifier is
treated as a custom user override, since it maps to a filepath and the
extraction algorithm doesn't know how to handle this.

### CODE REVIEW

File: src/install/lock.ts [hunk 1]
```diff
@@ -258,14 +256,18 @@ export async function extractLockConstraintsAndMap (map: IImportMap, preloadUrls
...
       const subpath = '.' + targetUrl.slice(pkgUrl.length - 1) as '.' | `./{string}`;
       pkgUrls.add(pkgUrl);
-      const exportSubpath = parsedTarget && await resolver.getExportResolution(pkgUrl, subpath, key);
-      if (exportSubpath) {
+      const exportSubpath = await resolver.getExportResolution(pkgUrl, subpath, key);
+
+      // If the plain specifier resolves to a package on some provider's CDN, 
+      // and we can find a suitable export for the module, then we can lock 
+      // the package down to an exact version:
+      if (parsedTarget && exportSubpath) {
```
Comment (guybedford) [inline src/install/lock.ts:264]: Maybe better to keep the existing logic unless there is a good reason to change it?

File: src/install/lock.ts [hunk 2]
```diff
@@ -258,14 +256,18 @@ export async function extractLockConstraintsAndMap (map: IImportMap, preloadUrls
...
         // Imports resolutions that resolve as expected can be skipped
         if (key[0] === '#')
           continue;
         // If there is no constraint, make one as the semver major on the current version
         if (!constraints.primary[parsedKey.pkgName])
-          constraints.primary[parsedKey.pkgName] = parsedTarget ? packageTargetFromExact(parsedTarget.pkg) : pkgUrl;
+          constraints.primary[parsedKey.pkgName] = packageTargetFromExact(parsedTarget.pkg);
```
Comment (guybedford) [inline src/install/lock.ts:270]: Well caught

File: src/install/lock.ts [hunk 3]
```diff
@@ -118,8 +118,6 @@ export function setConstraint (constraints: VersionConstraints, name: string, ta
 }
 
 export function setResolution (resolutions: LockResolutions, name: string, installUrl: `${string}/`, pkgScope: `${string}/` | null = null, installSubpath: `./${string}` | null = null) {
-  if (installSubpath === './std')
-    throw new Error('NEIN');
```
Comment (guybedford) [inline src/install/lock.ts:122]: Sehr gut

File: src/install/lock.ts [hunk 4]
```diff
@@ -288,7 +290,16 @@ export async function extractLockConstraintsAndMap (map: IImportMap, preloadUrls
           continue;
         }
       }
+
+      // Otherwise if the plain specifier is a reference to the base package
+      // containing the import map, we can safely ignore it, as the tracemap
+      // will always resolve such imports correctly at the top-level:
+      const pcfg = await resolver.getPackageConfig(pkgUrl);
```
Comment (guybedford) [inline src/install/lock.ts:297]: Rather than `pkgUrl` we should try operate on a version of `getPackageBase` scoped to the first package.json boundary only to match Node.js resolution semantics.

File: src/install/lock.ts [hunk 5]
```diff
@@ -288,7 +290,16 @@ export async function extractLockConstraintsAndMap (map: IImportMap, preloadUrls
...
+      if (pcfg && pcfg.name === parsedKey.pkgName) {
```
Comment (guybedford) [inline src/install/lock.ts:298]: We also need to handle subpath and environment deconstruction here like all other resolutions.

**Comment by Bubblyworld** [comment]
Tests seem rather flaky - can't reproduce the failures locally on either v16 or v14 🤔

**Review by guybedford — APPROVED** [review]
