### PR TITLE
fix: don't throw in the nodemodules provider when encountering targets from other registries

### LINKED ISSUE #241: Swapping between nodemodules and CDN providers throws
Using the `nodemodules` provider works fine if that's all you use, but as soon as you try to relink your import map to/from the `jspm.io` and `nodemodules` providers (i.e. going between local/remote workflows), it throws:

Screenshot 2023-02-28 at 17 30 19

### PR DESCRIPTION
**Pull request by Bubblyworld**
Fixes #241. This is my attempt to rewrite the nodemodules provider a bit after
our talk yesterday @guybedford. The idea is that we can just treat the
`nodemodules` provider as a special "local registry", which we call `node_modules`
in the codebase. Packages in the `node_modules` registry are named according to
the following scheme:

    <package-name>#<hash-of-location>

Other than having a hash in the name, everything else about the packages is
ordinary, so this lets us disambiguate between packages with the same name and
version but different location/contents in your local `node_modules`. It also
lets us include versioning in the package targets (which we don't use yet but
could).

When the provider is resolving a package from another registry, like `npm` or
`denoland`, it looks up the package in the base `node_modules` and throws if it
can't find it.

It's a bit of a hack because `nodemodules` basically "translates" between the 
other registries and this local one, but I think it's kinda clean? Hopefully there's
no obvious reason this doesn't work haha 😅

### CODE REVIEW

File: src/install/installer.ts [hunk 1]
```diff
@@ -491,10 +490,12 @@ export class Installer {
...
   }
 
-  private getBestExistingMatch(matchPkg: PackageTarget): ExactPackage | null {
+  private async getBestExistingMatch(
+    matchPkg: PackageTarget
+  ): Promise<ExactPackage | null> {
     let bestMatch: ExactPackage | null = null;
     for (const pkgUrl of this.pkgUrls) {
-      const pkg = this.resolver.parseUrlPkg(pkgUrl);
+      const pkg = await this.resolver.parseUrlPkg(pkgUrl);
```
Comment (guybedford) [inline src/install/installer.ts:498]: If we use the version field for the hash, we should be able to syncify this again.

Comment (Bubblyworld) [reply src/install/installer.ts:498]: Yeah, makes sense, I'll add some documentation about the intention for `ExactPackage` - that it should pin down a package uniquely against a registry. From that point of view `version` is the right field for the hash.
