### PR TITLE
fix: add strict type checking, fix bugs caused by typing, fix deno provider

### LINKED ISSUE #220: Deno `std@0.178.0` does not include `node` any more
Currently we resolve node builtins like `node:XXX` to the respective `https://deno.land/std@0.178.0/node/XXX.ts` module. As of [yesterday](https://github.com/denoland/deno_std/pull/3206) the latest version of `std` no longer contains node shims, and it's built in to `deno` now.

Planned fix is to just resolve specifiers like `node:XXX` to themselves, like we do for `npm:XXX` specifiers and such.

### PR DESCRIPTION
**Pull request by Bubblyworld**
Adds strict typing for `call`/`bind` uses, there were a number of type-related
bugs in the provider plugins that were caused by Typescript not typing these
by default (and as a result we were passing incorrect arguments in, or using
the return values incorrectly).

Fixes #220, which was caused by the Deno standard library removing `node`
polyfills in the latest version (0.178.0). We now default to resolving
node builtins as bare `"node:XXX"` specifiers, which are supported by Deno.

### CODE REVIEW

File: src/providers/node.ts [hunk 1]
```diff
@@ -93,19 +93,13 @@ export function resolveBuiltin(
...
-        },
-        installSubpath: `./node/${builtin}`,
-      },
-      alias: builtin,
-    };
+  // Deno supports all node builtins via bare "node:XXX" specifiers. As of
+  // std@0.178.0, the standard library no longer ships node polyfills, so we
+  // should always install builtins as base specifiers. This does mean that we
+  // no longer support old versions of deno unless they use --compat.
+  if (env.includes("deno")) {
```
Comment (guybedford) [inline src/providers/node.ts:100]: Let's merge this conditional with the node one, as it's the same path.

**Review by guybedford — APPROVED** [review]
